// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  var yargs;

  require('colors');

  yargs = require('yargs').usage('This application will append extra extname to all filtered out JPG files.\nThen you can check the result by your OS\'s search function easily.\nIn case there is anything wrong, you can rollback.\n\nThe default destination is here.\n\nP.S. The priority among -l, -d & -r is -l > -d > -r\n\n' + 'Usage: clean-jpg [--options] [destination]'.cyan).options('x', {
    alias: 'extname',
    describe: "the extname(s) of your RAW files, case-" + 'IN'.yellow + "sensitive\na comma-seperated list is acceptable\n" + 'e.g. "-x nef,cr2,dng"'.cyan + "\n",
    "default": 'arw'
  }).options('r', {
    alias: 'rename',
    "default": 'extra-jpg-cleaner-result',
    describe: 'the extname used when renaming\n'
  }).options('D', {
    alias: 'delete',
    boolean: true,
    describe: '!!!CAUTION!!!\n'.yellow.bold + ("delete files " + 'DIRECTLY'.yellow + " w/o any confirmation\nit WON'T move your files to the recycle bin or trash can\ngenerally this operation will be unrecoverable\ntry this only if you think your luck is overwhelming\nincase something goes wrong\ngo to buy a EasyRecovery or something similar\nthen test your overwhelming luck again...")
  }).options('l', {
    alias: 'list',
    describe: 'just print a list of result, will NOT delete anything',
    boolean: true
  }).options('v', {
    alias: 'verbose',
    describe: 'print when renaming / deleting',
    boolean: true
  }).options('h', {
    alias: 'help',
    describe: 'print this help message',
    boolean: true
  }).wrap(80);

  module.exports = yargs;

}).call(this);

//# sourceMappingURL=argv.map
